FROM fedora:latest

RUN dnf upgrade -y && \
    dnf install -y \
    cmake \
    ninja-build \
    qt5-qtbase-devel \
    qt5-qtsvg-devel \
    qt5-qtmultimedia-devel \
    gstreamer1-devel \
    gstreamer1-plugins-base-devel \
    spdlog-devel \
    taglib-devel \
    && dnf clean all

COPY ./ /openkj/
WORKDIR /openkj/
RUN cmake -DSPDLOG_USE_BUNDLED=true . -B build -G Ninja
RUN ninja -C build
