/* taglib_config.h
 *
 * OpenKJ vendors TagLib's source directly rather than using TagLib's own
 * CMake build, so this file is hand-written instead of generated by
 * TagLib's configure step. It enables format auto-detection in
 * TagLib::FileRef for every format module compiled into this project (see
 * the matching include_directories() list in the top-level CMakeLists.txt).
 */

#ifndef TAGLIB_TAGLIB_CONFIG_H
#define TAGLIB_TAGLIB_CONFIG_H

#define TAGLIB_WITH_APE 1
#define TAGLIB_WITH_ASF 1
#define TAGLIB_WITH_DSF 1
#define TAGLIB_WITH_MATROSKA 1
#define TAGLIB_WITH_MOD 1
#define TAGLIB_WITH_MP4 1
#define TAGLIB_WITH_RIFF 1
#define TAGLIB_WITH_SHORTEN 1
#define TAGLIB_WITH_TRUEAUDIO 1
#define TAGLIB_WITH_VORBIS 1

#endif
