#ifndef OKJVERSION_H
#define OKJVERSION_H

#define OKJ_VERSION_MAJOR 2
#define OKJ_VERSION_MINOR 50
#define OKJ_VERSION_BUILD 0
#define OKJ_VERSION_STRING "2.50"
#define OKJ_VERSION_BRANCH "stable"

#endif //OKJVERSION_H
