name: Windows build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Windows Builds
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: x86_64
            qt_arch: msvc2019_64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Qt
      uses:
